# Generated by Django 5.0.1 on 2024-01-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="profile_picture",
            field=models.ImageField(upload_to="uploads/profiles/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(upload_to="uploads/thumbnail/"),
        ),
    ]
