# Generated by Django 5.0.1 on 2024-01-20 14:12

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_gallery_alter_author_profile_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=tinymce.models.HTMLField(default="test"),
            preserve_default=False,
        ),
    ]
