# Generated by Django 5.0.1 on 2024-01-20 14:15

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="overview",
            field=tinymce.models.HTMLField(),
        ),
    ]
